language: shell

env:
  global:
    - HUGO_VERSION="0.41"
    - HUGO_PACKAGE="hugo.tar.gz"
    - HUGO_DIRECTORY="hugo"
    - HUGO_BINARY="hugo"

install:
  - curl --location "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output "${HUGO_PACKAGE}"
  - mkdir "${HUGO_DIRECTORY}"
  - tar -xzf "${HUGO_PACKAGE}" -C "${HUGO_DIRECTORY}"

script:
  - "./${HUGO_DIRECTORY}/${HUGO_BINARY}"
