languageCode: "en-us"
title: "Artur Dryomov"

baseUrl: "https://arturdryomov.dev"
permalinks:
  post: ":slug"

params:
  description: "Artur Dryomov on software design, development and deployment."
  googleSearchCode: "Noz-S7X4481rtWBcFiugLcNzvzXEG3Ukn-T6QVPPUOE"

social:
  twitter: "arturdryomov"

menu:
  left:
    - name: "Posts"
      url: "/"
  right:
    - name: "GitHub"
      url: "https://github.com/arturdryomov"
      weight: 3
    - name: "Twitter"
      url: "https://twitter.com/arturdryomov"
      weight: 2
    - name: "RSS"
      url: "/index.xml"
      weight: 1

theme: "barebones"

googleAnalytics: "UA-112239048-1"

disableHugoGeneratorInject: true
enableEmoji: true
footnoteReturnLinkContents: "â†©"

disableKinds:
  - taxonomy
  - taxonomyTerm
  - section

pygmentsCodeFences: true
pygmentsUseClasses: true
