languageCode: "en-us"
title: "Artur Dryomov"

baseUrl: "https://arturdryomov.dev"
permalinks:
  post: ":slug"

params:
  author: "Artur Dryomov"
  description: "Artur Dryomov on software design, development and deployment"

menu:
  left:
    - name: "Posts"
      url: "/"
  right:
    - name: "GitHub"
      url: "https://github.com/arturdryomov"
      weight: 2
    - name: "RSS"
      url: "feed://arturdryomov.dev/index.xml"
      weight: 1

theme: "barebones"

disableHugoGeneratorInject: true
enableEmoji: true
footnoteReturnLinkContents: "â†©"

disableKinds:
  - taxonomy
  - taxonomyTerm
  - section

pygmentsCodeFences: true
pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
