languageCode: "en-us"
title: "Artur Dryomov"

baseUrl: "https://arturdryomov.dev"
permalinks:
  post: ":slug"

params:
  author: "Artur Dryomov"
  description: "Artur Dryomov on software design, development and deployment"

disableHugoGeneratorInject: true

disableKinds:
  - "section"
  - "taxonomy"
  - "term"

enableEmoji: true
footnoteReturnLinkContents: "â†©"

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

menu:
  left:
    - name: "Posts"
      url: "/"
  right:
    - name: "GitHub"
      url: "https://github.com/arturdryomov"
      weight: 1
    - name: "RSS"
      url: "feed://arturdryomov.dev/index.xml"
      weight: 2

theme: "barebones"
