name: "Pull Request"

on:
  pull_request:

jobs:
  checks:
    name: "Run checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v6.0.2

      - name: "Check scripts"
        run: shellcheck scripts/*.sh

      - name: "Generate content"
        run: bash scripts/generate.sh
